# Generated by Django 4.2.7 on 2023-12-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_name', models.CharField(max_length=50)),
                ('site_alpha', models.CharField(max_length=10)),
                ('proposedRFS_date', models.DateField()),
                ('transportable_cow', models.CharField(max_length=50)),
                ('cow_name', models.CharField(max_length=100)),
            ],
        ),
    ]
