# Generated by Django 4.2.7 on 2024-01-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='booked_by',
        ),
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='emp_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='from_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='purpose',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='to_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
