# Generated by Django 4.2.7 on 2024-01-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_city_record_asset_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Resource',
        ),
    ]
