# Generated by Django 4.2.7 on 2024-01-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_booked_by_resource_asset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='add_notes',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='address_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='address_street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='address_suburb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='coverage_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='deployment_engineer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='easting',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='engineering_region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ground_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='huawei_rnc',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='northing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='property_file_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='radio_engineer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='temp_site',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='w850_cluster',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
