# Generated by Django 4.2.7 on 2024-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_site_add_notes_site_address_city_site_address_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='easting',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='ground_height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='northing',
            field=models.FloatField(null=True),
        ),
    ]
