# Generated by Django 4.2.7 on 2024-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_site_easting_alter_site_ground_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_alpha', models.CharField(max_length=10)),
                ('frequency_band', models.CharField(max_length=10)),
                ('vendor', models.CharField(max_length=15)),
                ('sector', models.IntegerField()),
                ('azimuth', models.IntegerField()),
                ('antenna_height', models.FloatField()),
                ('electrical_tilt', models.IntegerField()),
                ('mechanical_tilt', models.IntegerField()),
                ('antenna_type', models.CharField(max_length=50)),
                ('share_antenna', models.CharField(max_length=10)),
                ('radio_equipment', models.CharField(max_length=20)),
                ('split_sectors', models.CharField(max_length=10)),
                ('main_radio_type', models.CharField(max_length=20)),
                ('num_carriers', models.IntegerField()),
                ('capacity_card_type', models.CharField(max_length=20)),
                ('num_cards', models.IntegerField()),
                ('cabinet_suffix', models.CharField(max_length=20)),
            ],
        ),
    ]
