# Generated by Django 4.2.7 on 2024-02-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='proposedRFS_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
