# Generated by Django 4.2.7 on 2024-02-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_site_proposedrfs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('usage', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('frequency_range', models.CharField(max_length=50, null=True)),
                ('num_low_ports', models.IntegerField(max_length=10, null=True)),
                ('num_high_ports', models.IntegerField(max_length=10, null=True)),
                ('weight', models.FloatField(max_length=10, null=True)),
                ('dimesons', models.CharField(max_length=50, null=True)),
                ('band600_gain', models.FloatField(max_length=10, null=True)),
                ('band700_gain', models.FloatField(max_length=10, null=True)),
                ('band850_gain', models.FloatField(max_length=10, null=True)),
                ('band1800_gain', models.FloatField(max_length=10, null=True)),
                ('band2100_gain', models.FloatField(max_length=10, null=True)),
                ('band2300_gain', models.FloatField(max_length=10, null=True)),
                ('band2600_gain', models.FloatField(max_length=10, null=True)),
                ('band3500_gain', models.FloatField(max_length=10, null=True)),
                ('hbw', models.FloatField(max_length=10, null=True)),
                ('band600_vbw', models.FloatField(max_length=10, null=True)),
                ('band700_vbw', models.FloatField(max_length=10, null=True)),
                ('band850_vbw', models.FloatField(max_length=10, null=True)),
                ('band1800_vbw', models.FloatField(max_length=10, null=True)),
                ('band2100_vbw', models.FloatField(max_length=10, null=True)),
                ('band2300_vbw', models.FloatField(max_length=10, null=True)),
                ('band2600_vbw', models.FloatField(max_length=10, null=True)),
                ('band3500_vbw', models.FloatField(max_length=10, null=True)),
                ('freq_low', models.FloatField(max_length=10, null=True)),
                ('freq_high', models.FloatField(max_length=10, null=True)),
                ('connectiors', models.CharField(max_length=10, null=True)),
                ('bracket_weight', models.FloatField(max_length=10, null=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFReportDataCommon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=100, null=True)),
                ('address_suburb', models.CharField(max_length=100, null=True)),
                ('address_city', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('qualifications', models.CharField(max_length=100, null=True)),
                ('reviewer', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('site_type', models.CharField(max_length=100, null=True)),
                ('comments', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFReportDataSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, null=True)),
                ('sector_name', models.CharField(max_length=50, null=True)),
                ('sector_azimuth_range', models.CharField(max_length=50, null=True)),
                ('sector_azimuth', models.IntegerField(max_length=10, null=True)),
                ('sector_band', models.CharField(max_length=50, null=True)),
                ('sector_carrier_power', models.FloatField(max_length=10, null=True)),
                ('sector_num_of_carriers', models.IntegerField(max_length=10, null=True)),
                ('sector_tx_filter_loss', models.FloatField(max_length=10, null=True)),
                ('sector_combiner_loss', models.FloatField(max_length=10, null=True)),
                ('sector_feeder_loss', models.FloatField(max_length=10, null=True)),
            ],
        ),
    ]
