# Generated by Django 4.2.7 on 2024-03-05 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0013_alter_antennatable_band1800_gain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_description', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='work_request_attachments/')),
                ('assigned_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_engineer', to=settings.AUTH_USER_MODEL)),
                ('requesting_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_engineer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
