# Generated by Django 4.2.7 on 2024-05-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_feedertable_bbptable_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfreportdataspecific',
            name='report_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
