# Generated by Django 4.2.7 on 2024-05-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_rfreportdataspecific_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='site_alpha',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
